# Generated by Django 4.1.7 on 2023-02-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='원시 텍스트')),
                ('summary_text', models.TextField(verbose_name='요약 텍스트')),
                ('level', models.IntegerField(choices=[(0, '상관없음'), (1, '고등학생 이하'), (2, '대학생'), (3, '직장인')], verbose_name='수준')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_chats', to='chats.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '일일 채팅',
                'verbose_name_plural': '일일 채팅',
                'ordering': ('-created_at',),
            },
        ),
    ]
