# Generated by Django 4.1.7 on 2023-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychat',
            name='raw_text',
            field=models.TextField(blank=True, verbose_name='원시 텍스트'),
        ),
        migrations.AlterField(
            model_name='dailychat',
            name='summary_text',
            field=models.TextField(blank=True, verbose_name='요약 텍스트'),
        ),
    ]
